apiVersion: v1
kind: Pod
metadata:
  name: init-container-test
  namespace: sysdig-agent
  labels:
    app: test-init-container
spec:
  initContainers:
    - name: setup
      image: python:3.9-slim  
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing dependencies..." &&
          pip install requests &&
          echo "Setup complete.";
  containers:
    - name: main-app
      image: nginx
      ports:
        - containerPort: 80
